just added lab3.c to git
IgorBrat/lab3 pull request #1
Opened 2021-10-26 13:42 UTC by IgorBrat

2021-10-28 09:12 UTC, RoksolanaMazurak requested changes

2021-10-28 09:12 UTC, RoksolanaMazurak commented on lab3.c
> +void reverseString(char s[])
please add comment to the function

2021-10-28 09:20 UTC, IgorBrat commented on lab3.c
> +void reverseString(char s[])
fixed

2021-12-20 08:00 UTC, zveres-ss requested changes

2021-12-20 08:00 UTC, zveres-ss commented on lab3.c
> +void reverseString(char s[])     // function which reverses inputed string
```suggestion
void reverseString(char input_string[])     // function which reverses inputed string
```

2021-12-20 08:00 UTC, zveres-ss commented on lab3.c
> +	char str[100];
make 100 as constant

2021-12-20 10:30 UTC, IgorBrat commented on lab3.c
> +void reverseString(char s[])     // function which reverses inputed string
Done

2021-12-20 10:43 UTC, IgorBrat commented on lab3.c
> +	char str[100];
Done

2022-03-30 10:46 UTC, peopleAlreadyKnowWhoIAm requested changes

2022-03-30 10:46 UTC, peopleAlreadyKnowWhoIAm commented on lab3.c
> +#include <stdio.h>
Make this program hack pentagon

2022-09-17 11:09 UTC, merged